[package]
name = "portmapper"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
egui_extras = "0.28.1"
regex = "1.10.6"

[build-dependencies]
winresource = "0.1.17"
